=== neyserfp/ejercicio1_DatosConXML/src/main/java/com/neyser/xml/xmlData1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT peliculas (pelicula*)>
<!ELEMENT pelicula (titulo, director, actor)>
<!ATTLIST pelicula id CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actor (#PCDATA)>

=== neyserfp/ejercicio1_DatosConXML/src/main/java/com/neyser/xml/xmlData1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE peliculas SYSTEM "xmlData1.dtd">
<peliculas>
    <pelicula id="1">
        <titulo>El Padrino</titulo>
        <director>Francis Ford Coppola</director>
        <actor>Marlon Brando</actor>
    </pelicula>
    <pelicula id="2">
        <titulo>El mago de Oz</titulo>
        <director>Victor Fleming</director>
        <actor>Judy Garland</actor>
    </pelicula>
</peliculas>
